1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [1]:
import numpy as np

In [3]:
a1=np.array([[2,3,4],[4,5,6],[7,8,9]])

In [4]:
a1+a1

array([[ 4,  6,  8],
       [ 8, 10, 12],
       [14, 16, 18]])

array([[ 44,  53,  62],
       [ 70,  85, 100],
       [109, 133, 157]])

In [6]:
np.matmul(a1,a1)

array([[ 44,  53,  62],
       [ 70,  85, 100],
       [109, 133, 157]])

In [7]:
a1.T

array([[2, 4, 7],
       [3, 5, 8],
       [4, 6, 9]])

In [10]:
n1="my name is nitesh!"

In [11]:
sorted(n1.split())

['is', 'my', 'name', 'nitesh!']

In [12]:
n1.replace("!","")

'my name is nitesh'